version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:80"
    #volumes:
    #  - ./Data:/app/Data
